version: "3.9"

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/src/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - post # ← added new service here
      - login-history # ← added new service here
      - file-upload # ← added new service here
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 50052
      POST_HOST: post # ← add new env
      POST_PORT: 50051 # ← add new env
      HISTORY_HOST: login-history # ← add new env
      HISTORY_PORT: 50054 # ← add new env
      FILE_UPLOAD_HOST: file-upload # ← add new env
      FILE_UPLOAD_PORT: 50053 # ← add new env

  auth:
    build:
      context: .
      dockerfile: apps/auth/src/Dockerfile
    ports:
      - "50052:50052"

  post:
    build:
      context: .
      dockerfile: apps/post/src/Dockerfile
    ports:
      - "50051:50051"

  login-history:
    build:
      context: .
      dockerfile: apps/login-history/src/Dockerfile
    ports:
      - "50054:50054"

  file-upload:
    build:
      context: .
      dockerfile: apps/file-upload/src/Dockerfile
    ports:
      - "50053:50053"
